// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyF7lsUex6c68UsAbw-c05vkkp9TLZVlk',
    appId: '1:750935796554:web:1d647399a775a88ec76fb3',
    messagingSenderId: '750935796554',
    projectId: 'raagbreath',
    authDomain: 'raagbreath.firebaseapp.com',
    storageBucket: 'raagbreath.firebasestorage.app',
    measurementId: 'G-429FE16CVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC41UPpyI8dYnBWO0N1aDkhr33Is1sLYqY',
    appId: '1:750935796554:android:28ba87dc767b2154c76fb3',
    messagingSenderId: '750935796554',
    projectId: 'raagbreath',
    storageBucket: 'raagbreath.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbbQpZxK8-gKSVWs2aO_GrMWEE8H8Mxzw',
    appId: '1:750935796554:ios:fac780bba9f09b29c76fb3',
    messagingSenderId: '750935796554',
    projectId: 'raagbreath',
    storageBucket: 'raagbreath.firebasestorage.app',
    iosBundleId: 'com.raagbreath.app',
  );
}
